export function fetchNotifications() {
    return [
        {
          id: 1,
          title: "Placement Drive - Google",
          type: "placement",
          weight: 3,
          unread: true,
          time: Date.now() - 1000 * 60 * 2,
        },
        {
          id: 2,
          title: "Result Published - DBMS",
          type: "result",
          weight: 2,
          unread: true,
          time: Date.now() - 1000 * 60 * 20,
        },
        {
          id: 3,
          title: "Tech Fest Registration",
          type: "event",
          weight: 1,
          unread: true,
          time: Date.now() - 1000 * 60 * 5,
        },
        {
          id: 4,
          title: "Placement Drive - Microsoft",
          type: "placement",
          weight: 3,
          unread: true,
          time: Date.now() - 1000 * 60 * 10,
        },
        {
          id: 5,
          title: "Exam Time Table",
          type: "result",
          weight: 2,
          unread: false,
          time: Date.now() - 1000 * 60 * 1,
        },
        {
          id: 6,
          title: "Hackathon Event",
          type: "event",
          weight: 1,
          unread: true,
          time: Date.now() - 1000 * 60 * 30,
        },
        {
          id: 7,
          title: "Placement - Amazon",
          type: "placement",
          weight: 3,
          unread: true,
          time: Date.now() - 1000 * 60 * 15,
        },
        {
          id: 8,
          title: "Semester Result",
          type: "result",
          weight: 2,
          unread: true,
          time: Date.now() - 1000 * 60 * 40,
        },
        {
          id: 9,
          title: "Workshop Registration",
          type: "event",
          weight: 1,
          unread: true,
          time: Date.now() - 1000 * 60 * 7,
        },
        {
          id: 10,
          title: "Placement - TCS",
          type: "placement",
          weight: 3,
          unread: true,
          time: Date.now() - 1000 * 60 * 12,
        },
        {
          id: 11,
          title: "Placement - Infosys",
          type: "placement",
          weight: 3,
          unread: true,
          time: Date.now() - 1000 * 60 * 25,
        },
        {
          id: 12,
          title: "Cultural Event",
          type: "event",
          weight: 1,
          unread: true,
          time: Date.now() - 1000 * 60 * 3,
        },
      ];
    
}
